---
title: "1/4/2023"
output: pdf_document
date: "2023-01-04"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages(MASS)
library(MASS)


#test dd123

#install.packages("plyr")
#install.packages("dplyr")
#install.packages("haven")
#library(dplyr)
#library(plyr)
library(haven)
#install.packages(descr)
library(descr)
library(dplyr)
library(glmnet)
library(ggplot2)
```

## R Markdown



## Read data

```{r, inlcude = FALSE}



#wave1 = AddHealth
#wave4 = addhealth4


#wave5 = read_sav("~/R data/Data/mergedaddhealth.sas7bdat")

wave5addhealth <- read_sas("Data/mergedaddhealth.sas7bdat")


total = wave5addhealth



#wave1 = read.csv("~/R data/Data/addhealth_pds.csv")
#wave4 = read.csv("~/R data/Data/wave_4_data.csv")
#wave5 = read.csv("~/R data/Data/wave5addhealth.csv")



#wave1 = wave1[order(wave1$AID),]
#wave4 = wave4[order(wave4$AID),]
#wave5 = wave5[order(wave5$AID),]


#freq(as.ordered(d$H5OD4A))



#total = merge(wave1, wave5, by="AID")




##H1RF1 is biological mother schooling 1 means went to college or greater 2 is less than college

total$momcollege = NA
total$momcollege[total$H1NM4 %in% c(1,2,3,4,5,6,7)] = 2
total$momcollege[total$H1RM1 %in% c(1,2,3,4,5,6,7)] = 2
total$momcollege[total$H1NM4 %in% c(8,9)] = 1
total$momcollege[total$H1RM1 %in% c(8,9)] = 1



#total$momcollege[total$momcollege != 1] = 2



## H1NM4 is biological father schooling 1 means went to college or greater 2 is less than college


total$dadcollege = NA
total$dadcollege[total$H1RF1 %in% c(1,2,3,4,5,6,7)] = 2
total$dadcollege[total$H1NF4 %in% c(1,2,3,4,5,6,7)] = 2
total$dadcollege[total$H1RF1 %in% c(8,9)] = 1
total$dadcollege[total$H1NF4 %in% c(8,9)] = 1
freq(total$dadcollege)

#sum(total$dadcollege == 1, na.rm= TRUE)

## parent college if one or more parents went to college
## might want to make a mompartcollege if this is called later

total$parentcollege = NA


# added people with missing data on both parents were put in the 2 cagtegory
total$parentcollege = NA
total$parentcollege = ifelse(total$dadcollege %in% c(1) | total$momcollege %in% c(1),1,2)
freq(total$parentcollege)




total$dadcollege
total$momcollege
(total$dadcollege | total$momcollege == 1)
total$parentcollege
(total$momcollege & total$dadcollege == 2)

#total$race <- ifelse(total$hispanic  == 1, 1, ifelse(total$black   == 1,  2, ifelse(total$asian   == 1, 3, ifelse(total$white == 1, 4, NA))))



freq(total$parentcollege)

# college degree variable wave 5
freq(total$H5OD11)
total$collegedegree = NA
total$collegedegree[total$H5OD11 %in% c(10,11,12,13,14,15,16)] = 1
total$collegedegree[total$H5OD11 %in% c(9,8,7,6,5,4,3,2)] = 0

# education wave1 expelled
total$expelled = NA
total$expelled[total$H1ED9 %in% c(1)] = 1
total$expelled[total$H1ED9 %in% c(0)] = 2

# english?
total$english = NA
total$english[total$H1ED11 %in% c(1)] = 4
total$english[total$H1ED11 %in% c(2)] = 3
total$english[total$H1ED11 %in% c(3)] = 2
total$english[total$H1ED11 %in% c(4)] = 1

# math
total$math = NA
total$math[total$H1ED12 %in% c(1)] = 4
total$math[total$H1ED12 %in% c(2)] = 3
total$math[total$H1ED12 %in% c(3)] = 2
total$math[total$H1ED12 %in% c(4)] = 1

# social science 
total$socialst = NA
total$socialst[total$H1ED13 %in% c(1)] = 4
total$socialst[total$H1ED13 %in% c(2)] = 3
total$socialst[total$H1ED13 %in% c(3)] = 2
total$socialst[total$H1ED13 %in% c(4)] = 1

# science
total$science = NA
total$science[total$H1ED14 %in% c(1)] = 4
total$science[total$H1ED14 %in% c(2)] = 3
total$science[total$H1ED14 %in% c(3)] = 2
total$science[total$H1ED14 %in% c(4)] = 1

# gpa=mean (of english math socialst science)

# teacher trouble variable

total$teachertrouble = NA
total$teachertrouble[total$H1ED15 %in% c(2,3,4,5,6,7,8)] = 1
total$teachertrouble[total$H1ED15 %in% c(1,0)] = 2

# attention trouble
total$attentiontrouble = NA
total$attentiontrouble[total$H1ED16 %in% c(2,3,4,5,6,7,8)] = 1
total$attentiontrouble[total$H1ED16 %in% c(1,0)] = 2

# hw trouble
total$hwtrouble = NA
total$hwtrouble[total$H1ED17 %in% c(2,3,4,5,6,7,8)] = 1
total$hwtrouble[total$H1ED17 %in% c(1,0)] = 2

# social trouble
total$socialtrouble = NA
total$socialtrouble[total$H1ED18 %in% c(2,3,4,5,6,7,8)] = 1
total$socialtrouble[total$H1ED18 %in% c(1,0)] = 2


# closeschool
total$closeschool = NA
total$closeschool[total$H1ED19 %in% c(1,2)] = 1
total$closeschool[total$H1ED19 %in% c(3,4,5)] = 2

# partschool
total$partschool = NA
total$partschool[total$H1ED20 %in% c(1,2)] = 1
total$partschool[total$H1ED20 %in% c(3,4,5)] = 2

# Prej school
total$prejschool = NA
total$prejschool[total$H1ED21 %in% c(1,2)] = 1
total$prejschool[total$H1ED21 %in% c(3,4,5)] = 2

# happy school
total$happyschool = NA
total$happyschool[total$H1ED22 %in% c(1,2)] = 1
total$happyschool[total$H1ED22 %in% c(3,4,5)] = 2

# fair school
total$fairschool = NA
total$fairschool[total$H1ED23 %in% c(1,2)] = 1
total$fairschool[total$H1ED23 %in% c(3,4,5)] = 2

# safe school
total$safeschool = NA
freq(total$H1ED24)
total$safeschool[total$H1ED24 %in% c(1,2)] = 1
total$safeschool[total$H1ED24 %in% c(3,4,5)] = 2

# wave1 grade
total$wave1grade[total$wave1grade %in% c(96, 97,98,99)] = NA

## rename gender broken go back

#total = rename(total, gender = H5OD2A)


# race




total$white = 0
total$white[total$H5OD4A %in% c(1)] = 1

total$black = 0
total$black[total$H5OD4B %in% c(1)] = 1

total$hispanic = 0
total$hispanic[total$H5OD4C %in% c(1)] = 1

total$asain = 0
total$asain[total$H5OD4D %in% c(1)] = 1



total$race = NA
total$race <- ifelse(total$hispanic  == 1, 1, ifelse(total$black   == 1,  2, ifelse(total$asian   == 1, 3, ifelse(total$white == 1, 4, NA))))
total$race

  

# house hold income proxy
total$hhincome = NA
total$hhincome[total$H5EC2 %in% c(1)] = 2500
total$hhincome[total$H5EC2 %in% c(2)] = 7500
total$hhincome[total$H5EC2 %in% c(3)] = 12500
total$hhincome[total$H5EC2 %in% c(4)] = 17500
total$hhincome[total$H5EC2 %in% c(5)] = 22500
total$hhincome[total$H5EC2 %in% c(6)] = 27500
total$hhincome[total$H5EC2 %in% c(7)] = 35000
total$hhincome[total$H5EC2 %in% c(8)] = 45000
total$hhincome[total$H5EC2 %in% c(9)] = 62500
total$hhincome[total$H5EC2 %in% c(10)] = 87500
total$hhincome[total$H5EC2 %in% c(11)] = 125000
total$hhincome[total$H5EC2 %in% c(12)] = 175000
total$hhincome[total$H5EC2 %in% c(13)] = 250000

# gpa
df = data.frame(total$english,total$math,total$socialst,total$science)
df
df$gpa = apply(df,1,mean, na.rm = TRUE)
total$gpa = df$gpa






freq(total$white)
freq(total$black)
freq(total$hispanic)
freq(total$asain)
freq(total$race)
freq(total$gpa)
freq(total$H5OD11)
freq(total$collegedegree)
freq(total$parentcollege)
freq(total$gender)
freq(total$H1NM4)
freq(total$momcollege)
freq(total$H1NF4)
freq(total$dadcollege)
freq(total$H5HR1)
freq(total$H5LM10)
freq(total$H5EC1)
freq(total$H5EC2)

freq(total$hhincome)

freq(total$H5EC9)
freq(total$teachertrouble)
freq(total$attentiontrouble)
freq(total$hwtrouble)
freq(total$socialtrouble)
freq(total$closeschool)
freq(total$partschool)
freq(total$prejschool)
freq(total$happyschool)
freq(total$fairschool)
freq(total$safeschool)
freq(total$wave1grade)



```

```{r}

# ANOVA TABLE
res_aov <- aov(collegedegree ~ wave1grade+ gpa, data = total)
res_aov

# multi linear regression 
model  <- lm(collegedegree ~  race + gender + parentcollege + teachertrouble + attentiontrouble + hwtrouble + socialtrouble +
closeschool + partschool + prejschool + happyschool + fairschool + safeschool, data = total)
summary(model)


```




```{r}
# stepwise function

#define intercept-only model
levels(total$collegedegree)
(total$collegedegree)
intercept_only <- lm(collegedegree ~ 1, data=total)

#define model with all predictors
all <- lm(collegedegree ~ ., data=total)

#perform forward stepwise regression
forward <- step(intercept_only, direction='forward', scope=formula(all), trace=0)

#view results of forward stepwise regression
forward$anova


```





```{r}
# lasso regression
y <- total$collegedegree

x <- data.matrix(total[, c('collegedegree','race', 'gender' ,'parentcollege' ,'gpa', 'expelled', 'teachertrouble', 'attentiontrouble' ,'hwtrouble', 'socialtrouble',
'closeschool', 'partschool' ,'prejschool', 'happyschool' ,'fairschool', 'safeschool', 'wave1grade' )])

x = na.omit(x)
x = x[,-1]
y = x[,1]


nrow(x)
nrow(y)
#perform k-fold cross-validation to find optimal lambda value

cv_model <- cv.glmnet(x, y, alpha = 1)
#makeX(x)
#find optimal lambda value that minimizes test MSE
best_lambda <- cv_model$lambda.min
best_lambda



#produce plot of test MSE by lambda value
plot(cv_model) 


#find coefficients of best model
best_model <- glmnet(x, y, alpha = 1, lambda = best_lambda)
coef(best_model)


new = matrix(c(1,4, 1, 2.5, 2,2,2,1,1,2,1,2,2,1,2,9), nrow=1, ncol=16) 


#use lasso regression model to predict response value
predict(best_model, s = best_lambda, newx = new)

#use fitted best model to make predictions
y_predicted <- predict(best_model, s = best_lambda, newx = x)

#find SST and SSE
sst <- sum((y - mean(y))^2)
sse <- sum((y_predicted - y)^2)

#find R-Squared
rsq <- 1 - sse/sst
rsq

```


```{r}

total$gender
ggplot(total, aes(x = as.factor(race), y = collegedegree, fill = as.factor(gender))) + 
  geom_bar(stat = "identity")

```





